### ISSUE TITLE
Make List of available datasets scrollable

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#249]
The entire list of available datasets needs to be scroll-able.  Currently the footer is blocking the last few datasets (such as tweets).
![image](https://cloud.githubusercontent.com/assets/18470113/19053715/9667bef0-8981-11e6-85e2-752680d9fc80.png)

**Comment by tomschenkjr** [comment]
Was this just fixed in opengrid.io or was code submitted to fix it in the repo?

**Comment by PriyaDoIT** [comment]
@rladines to add this to the repo

**Comment by PriyaDoIT** [comment]
hello @rladines was this included in 1.3.0?

**Comment by rladines** [comment]
@PriyaDoIT I just checked the latest build and unfortunately this is still not fixed. I will check if this was missed during the auto-merge from the opengrid.io PR. I don't believe that's the case though.
